### ISSUE TITLE
Weka IBK giving recommendations for everything

### ISSUE THREAD

**Issue by NilayBhatt** [NilayBhatt/DiversifiedRecomendations#1]
@caw13 the recommendation algorithm gives recommendations for everything and it is not skipping for ones that have already been recommended

**Comment by NilayBhatt** [comment]
@caw13

**Comment by caw13** [comment]
@NilayBhatt try stepping through line 47 of this code and confirm if it is only stepping into that code if the ratings are actually missing https://github.com/NilayBhatt/DiversifiedRecomendations/blob/Weka/src/main/java/edu/ccsu/weka/WekaIBk.java#L47

**Comment by NilayBhatt** [comment]
Got it, its the duplicate movies. What should we do with the duplicate data?

**Comment by caw13** [comment]
@NilayBhatt For the purposes of this application I would think it would be fine to just remove (or surpress) duplicates

**Comment by NilayBhatt** [comment]
gotcha, I will filter the data in the database. Should I keep a record of what I am removing?

**Comment by caw13** [comment]
That would be good
